### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by ttsy-80** [pengzhendong/openfst-android#1]
大佬，你好，执行./gradlew build不通过，不知道什么原因？

 What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /Users/daiwenyin/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/daiwenyin/Desktop/openfst-android-master/app/.cxx/cmake/debug/arm64-v8a native-lib}
  ninja: Entering directory `/Users/daiwenyin/Desktop/openfst-android-master/app/.cxx/cmake/debug/arm64-v8a'
  [1/9] Performing build step for 'gflags'
  ninja: no work to do.
  [2/9] Performing build step for 'glog'
  ninja: no work to do.
  [3/9] No install step for 'gflags'
  [4/9] No install step for 'glog'
  [5/9] Completed 'gflags'
  [6/9] Completed 'glog'
  [7/9] Running utility command for openfst
  FAILED: CMakeFiles/openfst.util 
  cd /Users/daiwenyin/Desktop/openfst-android-master/app/.cxx/cmake/debug/arm64-v8a && cp -r /Users/daiwenyin/Desktop/openfst-android-master/app/.cxx/cmake/debug/arm64-v8a/openfst-src/src/include/fst /Users/daiwenyin/Desktop/openfst-android-master/app/src/main/cpp/../../../libs/include && cp -r /Users/daiwenyin/Desktop/openfst-android-master/app/.cxx/cmake/debug/arm64-v8a/gflags-prefix/src/gflags-build/include/gflags /Users/daiwenyin/Desktop/openfst-android-master/app/src/main/cpp/../../../libs/include && cp /Users/daiwenyin/Desktop/openfst-android-master/app/.cxx/cmake/debug/arm64-v8a/glog-prefix/src/glog/src/glog/log_severity.h /Users/daiwenyin/Desktop/openfst-android-master/app/.cxx/cmake/debug/arm64-v8a/glog-prefix/src/glog-build/glog && cp -r /Users/daiwenyin/Desktop/openfst-android-master/app/.cxx/cmake/debug/arm64-v8a/glog-prefix/src/glog-build/glog /Users/daiwenyin/Desktop/openfst-android-master/app/src/main/cpp/../../../libs/include && cp /Users/daiwenyin/Desktop/openfst-android-master/app/.cxx/cmake/debug/arm64-v8a/openfst-prefix/src/openfst-build/src/lib/.libs/libfst* /Users/daiwenyin/Desktop/openfst-android-master/app/src/main/cpp/../../../libs/arm64-v8a && cp /Users/daiwenyin/Desktop/openfst-android-master/app/.cxx/cmake/debug/arm64-v8a/gflags-prefix/src/gflags-build/lib/libgflags* /Users/daiwenyin/Desktop/openfst-android-master/app/src/main/cpp/../../../libs/arm64-v8a && cp /Users/daiwenyin/Desktop/openfst-android-master/app/.cxx/cmake/debug/arm64-v8a/glog-prefix/src/glog-build/libglog* /Users/daiwenyin/Desktop/openfst-android-master/app/src/main/cpp/../../../libs/arm64-v8a
  usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
         cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
  ninja: build stopped: subcommand failed.

**Comment by pengzhendong** [comment]
不好意思，刚看到消息。这个问题是编译完成后，拷贝的目标目录不存在，需要在 `app/libs` 中新建一个 `arm64-v8a` 和 `x86_64` 目录。

这里也有编译好的 arm64-v8a 和 x86_64 的库：
* 可以直接下载：https://github.com/pengzhendong/wenet-openfst-android/tree/master/app/libs
* 也可以在 `build.gradle` 中直接使用：

```
dependencies {
    implementation 'com.github.pengzhendong:wenet-openfst-android:1.0.1'
}
```
